baseURL = "http://example.org/"
languageCode = "en-us"
title = "My New Hugo Site"
publishDir = "../docs"
theme = "notheme"

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "pastie"
    tabWidth = 4