name: Test Gnofract 4D

on:
    pull_request:
      types: [opened, reopened, ready_for_review]
    push:

jobs:
  run:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
        python: [3.5, 3.6, 3.7]
        toxenv: [py]
        exclude:
          - os: macos-latest
            python: 3.5
          - os: macos-latest
            python: 3.6
        include:
          - os: ubuntu-latest
            python: 3.7
            toxenv: pylint

    env:
      # For labelling Codecov report
      OS: ${{ matrix.os }}
      PYTHON: ${{ matrix.python }}

    steps:
      - uses: actions/checkout@v2
      - name: Install MacOS packages
        if: ${{ matrix.os == 'macos-latest' }}
        run: brew install gtk+3 pygobject3
      - name: Install Ubuntu packages
        if: ${{ matrix.os == 'ubuntu-latest' }}
        # libgirepository1.0-dev required to build PyGObject from source
        run: sudo apt install gir1.2-gtk-3.0 libgirepository1.0-dev xvfb
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: Install Tox and any other PyPI packages
        run: pip install tox
      - name: Build
        run: python setup.py build
      - name: Run Tox (MacOS)
        if: ${{ matrix.os == 'macos-latest' }}
        run: tox -e ${{ matrix.toxenv }}
      - name: Run Tox (Linux)
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: xvfb-run --auto-servernum tox -e ${{ matrix.toxenv }}
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1.0.7
        with:
          file: ./coverage.xml
          env_vars: OS,PYTHON
