name: Test Gnofract 4D

on:
    pull_request:
      types: [opened, reopened, ready_for_review]
    push:

jobs:
  test:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: [3.5, 3.6, 3.7]
        toxenv: [py]
        include:
          - python: 3.7
            toxenv: pylint

    steps:
      - uses: actions/checkout@v2
      - name: Install Ubuntu packages
        # libgirepository1.0-dev required to build PyGObject from source
        run: sudo apt install gir1.2-gtk-3.0 libgirepository1.0-dev xvfb
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: Install Tox and any other PyPI packages
        run: pip install tox
      - name: Build
        run: python setup.py build
      - name: Run Tox
        run: xvfb-run --auto-servernum tox -e ${{ matrix.toxenv }}
